In [4]:
import pandas as pd

dataset = pd.read_csv("google-play-store.csv")
dataset = dataset.dropna(subset=['genre', 'min_installs'])

In [5]:
# Task 1 قسمت التطبيقات حسب الفئه وحسبت المتوسط ورتبت تنازلي
dataset.groupby('genre')['min_installs'].median().sort_values(ascending=False).head(10)

genre
Action          1000000.0
Casual          1000000.0
Racing          1000000.0
Casino           500000.0
Simulation       500000.0
Role Playing     500000.0
Strategy         500000.0
Arcade           500000.0
Word             500000.0
Music            100000.0
Name: min_installs, dtype: float64

In [8]:
# Task 2 رتبت تصاعدي
dataset.groupby('genre')['min_installs'].median().sort_values(ascending=True).head(10)

genre
Business            1000.0
Medical             1000.0
Food & Drink        1000.0
Events              1000.0
House & Home        5000.0
Auto & Vehicles     5000.0
Education           5000.0
Art & Design       10000.0
Finance            10000.0
Lifestyle          10000.0
Name: min_installs, dtype: float64

In [9]:
# Task 3 بحسب اكبر تطبيق من حيث عدد التنزيلات عن طريق اكبر رقم والمتوسط وقسمه اكبر رقم علي المتوسط  وطباعه 5 اعداد
max_installs = dataset.groupby('genre')['min_installs'].max()
median_installs = dataset.groupby('genre')['min_installs'].median()

leader_ratio = (max_installs / median_installs).sort_values(ascending=False)

leader_ratio.head(5)

genre
Books & Reference    100000.0
Business             100000.0
Communication        100000.0
Music & Audio        100000.0
News & Magazines     100000.0
Name: min_installs, dtype: float64

In [8]:
# Task 4 حساب المتوسط
dataset['min_installs'].median()

50000.0

In [9]:
# Task 5 اعلي تنزيل من التطبيقات من حيث التطبيقات المدفوعه 
dataset.groupby(dataset['price'] > 0)['min_installs'].median()

price
False    50000.0
True      1000.0
Name: min_installs, dtype: float64

In [33]:
# Task 6 اي التطبيقات اعلي تقييم ترتيب تنازلي واظهار اعلي 5 تطبيقات 
dataset.groupby('genre')['score'].mean().sort_values(ascending=False).head(5)

genre
Books & Reference    4.515021
Word                 4.494153
Personalization      4.476157
Music & Audio        4.459054
Casino               4.450163
Name: score, dtype: float64

In [10]:
# Task 7 اي تطبيقات يوجد بها اعلي تفاعل وهعرض 5 تطبيقات منهم ترتيب تنازلي
dataset.sort_values(by='reviews', ascending=False)[['title', 'reviews']].head(6)

                                          title     reviews
5298                                   Facebook  22053770.0
7119                                  Instagram  21702496.0
5058                         WhatsApp Messenger  19031005.0
12054                            Clash of Clans  17895834.0
5293   Messenger – Text and Video Chat for Free  15404150.0
4484    Clean Master- Space Cleaner & Antivirus  11064681.0

In [12]:
# Task 8 كم تطبيق يعتمد علي علي الoffers_iap
dataset['offers_iap'].sum()

np.int64(13603)

In [11]:
# Task 9 بحسب اجمالي عدد التحميلات وبرتب ترتيب تنازلي وبعرض اول 7 تطبيقات
dataset.groupby('genre')['min_installs'].sum().sort_values(ascending=False).head(7)

genre
Tools            19324157224
Communication    12171306200
Productivity     10529523940
Casual            6337830360
Photography       5939279081
Arcade            5563164090
Social            5305541910
Name: min_installs, dtype: int64

In [14]:
# Task 10 بجيب تاريخ اقدم واحدث تطبيق من حيث الرفع
dataset['released'] = pd.to_datetime(dataset['released'])
dataset['released'].min(), dataset['released'].max()

(Timestamp('2010-01-28 00:00:00'), Timestamp('2018-11-12 00:00:00'))

In [37]:
# Task 11 بجيب متوسط التقييمات
dataset[dataset['reviews'] > 10000]['ratings_per_day'].mean()

np.float64(328.08230958230956)

In [12]:
# Task 12  اعلي 4 تطبيقات من حيث الاسكور
dataset.groupby('genre')['score'].mean().sort_values(ascending=False).head(4)

genre
Books & Reference    4.515021
Word                 4.494153
Personalization      4.476157
Music & Audio        4.459054
Name: score, dtype: float64

In [13]:
# Task 13 تم الاستعانه بشات وفهمت قد اي التطبيقات بتستخدم طريق ربح مزدوج مثل الاعلانات و الشراء الاوفلاين
both = dataset[(dataset['ad_supported'] == True) &
(dataset['offers_iap'] == True)]
percentage = (len(both) / len(dataset)) * 100
percentage

16.963616352702854

In [44]:
# Task 14 السنه اللي فيها اعلي نسبه نشر تطبيقات 
dataset['release_year'] = dataset['released'].dt.year

dataset['release_year'].value_counts().head(1)

release_year
2018.0    20861
Name: count, dtype: int64

In [45]:
# Task 15 بجيب اعلي التطبيقات عليها ريفيو وبشوف الاعلي سكور فيها وبطبعله 5 منهم
def genre_corr(group):
    return group['reviews'].corr(group['score'])

dataset.groupby('genre')[['reviews','score']].apply(genre_corr).head(5)

genre
Action             0.091880
Adventure          0.007085
Arcade             0.048083
Art & Design       0.048681
Auto & Vehicles    0.047442
dtype: float64

In [26]:
# Task 16 تم الاستعانه ب شات وحاولت افهمه لكن للاسف ماباليد حيله
weighted_rating = dataset.groupby('genre') \
    .apply(lambda x: (x['score'] * x['reviews']).sum() / x['reviews'].sum())
 
weighted_rating.sort_values(ascending=False).head(10)

C:\Users\Admin\AppData\Local\Temp\ipykernel_19192\2267561578.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: (x['score'] * x['reviews']).sum() / x['reviews'].sum())

genre
Parenting            4.609931
Education            4.576264
Books & Reference    4.534737
Strategy             4.515109
Health & Fitness     4.502468
Casino               4.500013
Personalization      4.493771
Word                 4.489004
Tools                4.487024
Board                4.477865
dtype: float64

In [14]:
# Task 17 بجيب اعلي نسبه تقييم بالنسبه لاعلي نسبه تفاعل وبعرض منها 5 تطبيقات
dataset['rating_review_ratio'] = dataset['ratings'] / dataset['reviews']

dataset.loc[dataset.groupby('genre')['rating_review_ratio'].idxmax(),['genre', 'title', 'rating_review_ratio']].head(5)

,genre,title,rating_review_ratio
60418,Action,Wilderness Hunter 2016,inf
62329,Adventure,The Adventure Coin and Theft,26.5
47995,Arcade,Retro GEN Pro - MD Emulator,inf
30627,Art & Design,Graffiti Alphabet Letters Drawing Ideas,inf
223,Auto & Vehicles,SphereDR,inf